-- =============================================================================
-- SPORTMAPS SEED SCRIPT
-- =============================================================================
-- Production Mode: Empty seed file to prevent demo data injection.
-- To add administrator accounts or static data, use migrations or a separate script.
-- =============================================================================
