// ═══════════════════════════════════════════════════════════════════════════════
// CATÁLOGO GLOBAL DE DEPORTES — Filtrado LATAM
// Fuente: IOC, ASOIF, ARISF, AIMS, IPC, Federaciones Internacionales
// Generado: 2026-03-10
// ═══════════════════════════════════════════════════════════════════════════════

export type CategoriaGlobal =
  | 'olimpicos_verano'
  | 'olimpicos_invierno'
  | 'paralimpicos'
  | 'reconocidos_COI_no_olimpicos'
  | 'no_olimpicos_federacion_internacional'
  | 'deportes_mentales_y_estrategia'
  | 'deportes_motorizados'
  | 'artes_marciales_y_combate'
  | 'deportes_de_naturaleza';

export interface SportCatalogEntry {
  id: number;
  nombre: string;
  nombreIngles: string;
  slug: string;
  federacion: string;
  acronimo: string;
  estadoOlimpico: string;
  categoriaGlobal: CategoriaGlobal;
  categoriasCompetencia: Record<string, string[] | Record<string, unknown>>;
}

export const SPORTS_CATALOG: SportCatalogEntry[] = [
  {
    id: 1,
    nombre: "Atletismo",
    nombreIngles: "Athletics",
    slug: "atletismo",
    federacion: "World Athletics",
    acronimo: "WA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      pruebas_pista: [
        "100m",
        "200m",
        "400m",
        "800m",
        "1500m",
        "3000m obstáculos",
        "5000m",
        "10000m",
        "110m vallas (H)",
        "100m vallas (M)",
        "400m vallas",
        "4x100m relevos",
        "4x400m relevos",
        "4x400m relevos mixto",
      ],
      pruebas_campo: [
        "Salto de altura",
        "Salto con garrocha",
        "Salto de longitud",
        "Triple salto",
        "Lanzamiento de peso",
        "Lanzamiento de disco",
        "Lanzamiento de martillo",
        "Lanzamiento de jabalina",
      ],
      pruebas_combinadas: ["Decatlón (H)", "Heptatlón (M)"],
      pruebas_ruta: ["Maratón", "Marcha 20km", "Marcha 35km"],
      categorias_edad: [
        "Sub-18 (Juvenil)",
        "Sub-20 (Junior)",
        "Sub-23",
        "Senior",
        "Masters (35+, 40+, 45+, 50+, 55+, 60+, 65+, 70+, 75+, 80+, 85+, 90+)",
      ],
      genero: ["Masculino", "Femenino", "Mixto (relevos)"],
    },
  },
  {
    id: 2,
    nombre: "Natación",
    nombreIngles: "Swimming",
    slug: "natacion",
    federacion: "World Aquatics",
    acronimo: "WA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      distancias_estilos: [
        "50m libre",
        "100m libre",
        "200m libre",
        "400m libre",
        "800m libre (M)",
        "1500m libre (H)",
        "100m espalda",
        "200m espalda",
        "100m pecho",
        "200m pecho",
        "100m mariposa",
        "200m mariposa",
        "200m combinado individual",
        "400m combinado individual",
        "4x100m libre",
        "4x200m libre",
        "4x100m combinado",
        "4x100m combinado mixto",
      ],
      categorias_edad: [
        "Sub-14",
        "Sub-16",
        "Sub-18 (Juvenil)",
        "Sub-20 (Junior)",
        "Senior",
        "Masters (25+, 30+, 35+, 40+, 45+, 50+, 55+, 60+, 65+, 70+, 75+, 80+, 85+, 90+, 95+, 100+)",
      ],
      genero: ["Masculino", "Femenino", "Mixto (relevos)"],
    },
  },
  {
    id: 3,
    nombre: "Natación en Aguas Abiertas",
    nombreIngles: "Open Water Swimming",
    slug: "natacion_en_aguas_abiertas",
    federacion: "World Aquatics",
    acronimo: "WA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      distancias: ["5km", "10km", "25km"],
      categorias_edad: ["Sub-18 (Juvenil)", "Sub-20 (Junior)", "Senior", "Masters"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 4,
    nombre: "Saltos Acuáticos",
    nombreIngles: "Diving",
    slug: "saltos_acuaticos",
    federacion: "World Aquatics",
    acronimo: "WA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: [
        "Trampolín 1m (H/M)",
        "Trampolín 3m (H/M)",
        "Trampolín 3m sincronizado (H/M)",
        "Plataforma 10m (H/M)",
        "Plataforma 10m sincronizado (H/M)",
        "Trampolín 3m sincronizado mixto",
        "Plataforma 10m sincronizado mixto",
      ],
      categorias_edad: ["Sub-14", "Sub-16", "Sub-18 (Juvenil)", "Sub-20 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 5,
    nombre: "Waterpolo",
    nombreIngles: "Water Polo",
    slug: "waterpolo",
    federacion: "World Aquatics",
    acronimo: "WA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Equipos de 13 jugadores (7 en agua)"],
      categorias_edad: ["Sub-15", "Sub-17", "Sub-19 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 6,
    nombre: "Natación Artística (Sincronizada)",
    nombreIngles: "Artistic Swimming",
    slug: "natacion_artistica_sincronizada",
    federacion: "World Aquatics",
    acronimo: "WA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Dúo técnico", "Dúo libre", "Equipo técnico (8)", "Equipo libre (8)", "Rutina de acrobacia mixta"],
      categorias_edad: ["Sub-15 (Juvenil)", "Sub-19 (Junior)", "Senior"],
      genero: ["Femenino", "Mixto (acrobacia)"],
    },
  },
  {
    id: 7,
    nombre: "Tiro con Arco",
    nombreIngles: "Archery",
    slug: "tiro_con_arco",
    federacion: "World Archery Federation",
    acronimo: "WA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: [
        "Recurvo individual (H/M)",
        "Recurvo por equipos (H/M)",
        "Recurvo mixto",
        "Compuesto individual (H/M)",
        "Compuesto por equipos (H/M)",
        "Compuesto mixto",
        "Bare bow individual (H/M)",
        "Instintivo",
      ],
      distancias: ["18m (indoor)", "25m (indoor)", "50m (outdoor)", "70m (outdoor)"],
      categorias_edad: ["Sub-18 (Cadet)", "Sub-21 (Junior)", "Senior", "Masters (50+, 60+, 70+)"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 8,
    nombre: "Bádminton",
    nombreIngles: "Badminton",
    slug: "badminton",
    federacion: "Badminton World Federation",
    acronimo: "BWF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Singles masculino", "Singles femenino", "Dobles masculino", "Dobles femenino", "Dobles mixto"],
      categorias_edad: ["Sub-15", "Sub-17", "Sub-19 (Junior)", "Sub-22", "Senior", "Para-bádminton"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 9,
    nombre: "Baloncesto",
    nombreIngles: "Basketball",
    slug: "baloncesto",
    federacion: "FIBA",
    acronimo: "FIBA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["5x5 (Basketball)", "3x3 (3x3 Basketball)"],
      categorias_edad: ["Sub-14", "Sub-16", "Sub-17", "Sub-18", "Sub-19 (U19 World Cup)", "Sub-23", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 10,
    nombre: "Boxeo",
    nombreIngles: "Boxing",
    slug: "boxeo",
    federacion: "World Boxing",
    acronimo: "WB",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      categorias_peso_masculino: [
        "48kg (Mínimo/Mini Mosca)",
        "51kg (Peso Mosca)",
        "54kg (Peso Gallo)",
        "57kg (Peso Pluma)",
        "60kg (Peso Ligero)",
        "63.5kg (Superligero/Jr Welter)",
        "67kg (Peso Welter)",
        "71kg (Super Welter/Jr Medio)",
        "75kg (Peso Medio)",
        "80kg (Super Medio/Jr Semipesado)",
        "86kg (Peso Semipesado)",
        "92kg (Jr Pesado/Crucero)",
        "+92kg (Peso Pesado)",
      ],
      categorias_peso_femenino: ["48kg", "50kg", "52kg", "54kg", "57kg", "60kg", "63kg", "66kg", "70kg", "75kg", "81kg", "+81kg"],
      categorias_edad: ["Youth (17-18)", "Junior (19-22)", "Elite (Senior)", "Masters"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 11,
    nombre: "Piragüismo Esprint",
    nombreIngles: "Canoe Sprint",
    slug: "piraguismo_esprint",
    federacion: "International Canoe Federation",
    acronimo: "ICF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      embarcaciones: ["Kayak 1 (K1)", "Kayak 2 (K2)", "Kayak 4 (K4)", "Canoa 1 (C1)", "Canoa 2 (C2)"],
      distancias: ["200m", "500m", "1000m", "5000m", "Maratón (36km)"],
      categorias_edad: ["Sub-23 (Junior)", "Sub-26 (U26)", "Senior", "Masters"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 12,
    nombre: "Piragüismo Eslalon",
    nombreIngles: "Canoe Slalom",
    slug: "piraguismo_eslalon",
    federacion: "International Canoe Federation",
    acronimo: "ICF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Kayak (K1)", "Canoa (C1)", "Kayak Cross (KX)", "Canoa Cross (CX)"],
      categorias_edad: ["Sub-18 (Junior)", "Sub-23 (U23)", "Senior"],
      genero: ["Masculino", "Femenino", "Mixto (team event)"],
    },
  },
  {
    id: 13,
    nombre: "Ciclismo en Ruta",
    nombreIngles: "Road Cycling",
    slug: "ciclismo_en_ruta",
    federacion: "Union Cycliste Internationale",
    acronimo: "UCI",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      pruebas: ["Carrera en línea", "Contrarreloj individual", "Contrarreloj por equipos"],
      categorias_edad: ["Sub-17", "Sub-19 (Junior)", "Sub-23 (Espoir)", "Elite/Senior", "Masters (30+, 40+, 50+, 60+)"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 14,
    nombre: "Ciclismo en Pista",
    nombreIngles: "Track Cycling",
    slug: "ciclismo_en_pista",
    federacion: "Union Cycliste Internationale",
    acronimo: "UCI",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      pruebas: [
        "Sprint individual",
        "Sprint por equipos",
        "Keirin",
        "Velocidad por equipos",
        "Omnium",
        "Madison",
        "Persecución individual",
        "Persecución por equipos",
        "1km contrarreloj",
        "500m contrarreloj",
      ],
      categorias_edad: ["Sub-17", "Sub-19 (Junior)", "Sub-23", "Elite/Senior", "Masters"],
      genero: ["Masculino", "Femenino", "Mixto (madison mixto)"],
    },
  },
  {
    id: 15,
    nombre: "BMX Racing",
    nombreIngles: "BMX Racing",
    slug: "bmx_racing",
    federacion: "Union Cycliste Internationale",
    acronimo: "UCI",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      categorias_edad: ["5-6 (Mini)", "7-8", "9-10", "11-12", "13-14 (Cadet)", "15-16 (Junior)", "17-24 (Elite Junior)", "25+ (Elite)"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 16,
    nombre: "BMX Freestyle",
    nombreIngles: "BMX Freestyle",
    slug: "bmx_freestyle",
    federacion: "Union Cycliste Internationale",
    acronimo: "UCI",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Park", "Flatland", "Street", "Vert", "Dirt"],
      categorias_edad: ["Sub-18 (Junior)", "Elite/Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 17,
    nombre: "Mountain Bike",
    nombreIngles: "Mountain Bike",
    slug: "mountain_bike",
    federacion: "Union Cycliste Internationale",
    acronimo: "UCI",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Cross Country (XCO)", "Downhill (DH)", "Enduro", "Four Cross (4X)", "E-MTB"],
      categorias_edad: ["Sub-17", "Sub-19 (Junior)", "Sub-23 (U23)", "Elite/Senior", "Masters (30+, 40+, 50+)"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 18,
    nombre: "Hípica - Doma",
    nombreIngles: "Dressage",
    slug: "hipica_doma",
    federacion: "Fédération Equestre Internationale",
    acronimo: "FEI",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      niveles: ["Introductorio", "Preliminar", "Novice", "Elementary", "Medium", "Advanced", "PSG", "Inter I", "Inter II", "Grand Prix"],
      modalidades_olimpicas: ["Gran Premio", "Gran Premio Especial", "Gran Premio Freestyle (Kür)", "Equipo"],
      categorias_edad: ["Pony (hasta 148cm)", "Junior (14-21)", "Young Riders (16-21)", "Under 25", "Senior"],
      genero: ["Mixto"],
    },
  },
  {
    id: 19,
    nombre: "Hípica - Concurso Completo",
    nombreIngles: "Eventing",
    slug: "hipica_concurso_completo",
    federacion: "Fédération Equestre Internationale",
    acronimo: "FEI",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      niveles: ["1*", "2*", "3*", "4*", "5*"],
      fases: ["Dressage", "Cross-country", "Salto"],
      modalidades: ["Individual", "Equipos"],
      categorias_edad: ["Junior (14-18)", "Young Riders (16-21)", "Senior"],
      genero: ["Mixto"],
    },
  },
  {
    id: 20,
    nombre: "Hípica - Salto",
    nombreIngles: "Show Jumping",
    slug: "hipica_salto",
    federacion: "Fédération Equestre Internationale",
    acronimo: "FEI",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      niveles: ["1* (1.20m)", "2* (1.30m)", "3* (1.40m)", "4* (1.50m)", "5* (1.60m+)"],
      modalidades: ["Individual", "Equipos", "Nations Cup"],
      categorias_edad: ["Children (12-14)", "Junior (14-18)", "Young Riders (16-21)", "Senior", "Amateur"],
      genero: ["Mixto"],
    },
  },
  {
    id: 21,
    nombre: "Esgrima",
    nombreIngles: "Fencing",
    slug: "esgrima",
    federacion: "Fédération Internationale d'Escrime",
    acronimo: "FIE",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      armas: ["Florete", "Espada", "Sable"],
      modalidades: ["Individual masculino", "Individual femenino", "Por equipos masculino", "Por equipos femenino"],
      categorias_edad: ["M11-12 (Pupilles)", "M13-14 (Minimes)", "M15-16 (Cadets)", "M17-20 (Juniors)", "Senior", "Veterans (50+, 60+, 70+)"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 22,
    nombre: "Fútbol",
    nombreIngles: "Football (Soccer)",
    slug: "futbol",
    federacion: "FIFA",
    acronimo: "FIFA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["11v11 (Fútbol)", "Fútbol Sala (Futsal)", "Fútbol Playa"],
      categorias_edad: [
        "Sub-11",
        "Sub-13",
        "Sub-15",
        "Sub-17",
        "Sub-20",
        "Sub-23 (Olímpico masculino)",
        "Sub-17 femenino",
        "Sub-20 femenino",
        "Senior (Femenino sin límite en JJOO)",
      ],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 23,
    nombre: "Golf",
    nombreIngles: "Golf",
    slug: "golf",
    federacion: "R&A / USGA (World Golf)",
    acronimo: "IGF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      formatos: ["72 hoyos stroke play individual", "Match play", "Stableford", "Four-ball", "Foursomes", "Scramble"],
      modalidades: ["Individual", "Por equipos", "Mixtos"],
      categorias_edad: ["Amateur (Sub-18)", "Sub-25 (Amateur Elite)", "Profesional", "Senior PGA (50+)", "Super Senior (60+)"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 24,
    nombre: "Gimnasia Artística",
    nombreIngles: "Artistic Gymnastics",
    slug: "gimnasia_artistica",
    federacion: "Fédération Internationale de Gymnastique",
    acronimo: "FIG",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      aparatos_masculinos: ["Suelo", "Caballo con arcos", "Anillas", "Salto de potro", "Barras paralelas", "Barra fija", "All-around"],
      aparatos_femeninos: ["Salto de potro", "Barras asimétricas", "Barra de equilibrio", "Suelo", "All-around"],
      modalidades: ["Individual All-around", "Por aparatos", "Por equipos"],
      categorias_edad: ["Sub-10 (Beginners)", "Sub-12", "Sub-14 (Junior International)", "Sub-16 (Senior Junior)", "Senior (16+)"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 25,
    nombre: "Gimnasia Rítmica",
    nombreIngles: "Rhythmic Gymnastics",
    slug: "gimnasia_ritmica",
    federacion: "Fédération Internationale de Gymnastique",
    acronimo: "FIG",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      aparatos: ["Aro", "Pelota", "Mazas", "Cinta", "Sin aparato"],
      modalidades: ["Individual All-around", "Individual por aparatos", "Grupos (5 gimnastas)"],
      categorias_edad: ["Junior (hasta 15)", "Senior (15+)"],
      genero: ["Femenino", "Mixto (grupos mixtos en algunas federaciones)"],
    },
  },
  {
    id: 26,
    nombre: "Trampolín",
    nombreIngles: "Trampoline",
    slug: "trampolin",
    federacion: "Fédération Internationale de Gymnastique",
    acronimo: "FIG",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Trampolín individual", "Doble mini-trampolín (DMT)", "Tumbling", "Sincronizado"],
      categorias_edad: ["Age Groups (7-8, 9-10, 11-12, 13-14, 15-16, 17-21)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 27,
    nombre: "Balonmano",
    nombreIngles: "Handball",
    slug: "balonmano",
    federacion: "International Handball Federation",
    acronimo: "IHF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["7v7 (Indoor)", "Beach Handball (4v4)", "Mini-handball"],
      categorias_edad: ["Mini (Sub-8)", "Sub-12", "Sub-14", "Sub-16", "Sub-18 (Juvenil)", "Sub-20 (Junior)", "Sub-21 masculino", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 28,
    nombre: "Hockey sobre Hierba",
    nombreIngles: "Field Hockey",
    slug: "hockey_sobre_hierba",
    federacion: "International Hockey Federation",
    acronimo: "FIH",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["11v11 (Field Hockey)", "Hockey 5s (Indoor reducido)", "Hockey en sala (Indoor 6v6)"],
      categorias_edad: ["Sub-17 (Junior)", "Sub-21 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 29,
    nombre: "Judo",
    nombreIngles: "Judo",
    slug: "judo",
    federacion: "International Judo Federation",
    acronimo: "IJF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      categorias_peso_masculino: ["-60kg", "-66kg", "-73kg", "-81kg", "-90kg", "-100kg", "+100kg"],
      categorias_peso_femenino: ["-48kg", "-52kg", "-57kg", "-63kg", "-70kg", "-78kg", "+78kg"],
      modalidades_adicionales: [
        "Por equipos mixto",
        "Por equipos masculino",
        "Por equipos femenino",
        "Kata (Nage-no-kata, Katame-no-kata, Kime-no-kata, Ju-no-kata, Kodokan Goshin-jutsu, Itsutsu-no-kata, Koshiki-no-kata, Seiryoku-zen'yo-kokumin-taiiku-no-kata, Joshi-judo-randori-no-kata)",
      ],
      categorias_edad: [
        "Pre-Mini (Sub-10)",
        "Mini (Sub-12)",
        "Cadet (Sub-15)",
        "Junior (Sub-18)",
        "U21",
        "Senior",
        "Masters (30+, 40+, 50+, 60+, 70+)",
      ],
      genero: ["Masculino", "Femenino", "Mixto (equipos)"],
    },
  },
  {
    id: 30,
    nombre: "Lucha Libre",
    nombreIngles: "Freestyle Wrestling",
    slug: "lucha_libre",
    federacion: "United World Wrestling",
    acronimo: "UWW",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      categorias_peso_masculino: ["-57kg", "-65kg", "-74kg", "-86kg", "-97kg", "-125kg"],
      categorias_peso_femenino: ["-50kg", "-53kg", "-57kg", "-62kg", "-68kg", "-76kg"],
      categorias_edad: ["Cadet (Sub-17)", "Junior (Sub-20)", "U23", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 31,
    nombre: "Lucha Grecorromana",
    nombreIngles: "Greco-Roman Wrestling",
    slug: "lucha_grecorromana",
    federacion: "United World Wrestling",
    acronimo: "UWW",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      categorias_peso: ["-60kg", "-67kg", "-77kg", "-87kg", "-97kg", "-130kg"],
      categorias_edad: ["Cadet (Sub-17)", "Junior (Sub-20)", "U23", "Senior"],
      genero: ["Masculino"],
    },
  },
  {
    id: 32,
    nombre: "Pentatlón Moderno",
    nombreIngles: "Modern Pentathlon",
    slug: "pentatlon_moderno",
    federacion: "Union Internationale de Pentathlon Moderne",
    acronimo: "UIPM",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      disciplinas: ["Esgrima (épée)", "Natación (200m)", "Equitación (show jumping)", "Carrera láser (run & shoot)"],
      modalidades: ["Individual", "Por equipos mixto"],
      categorias_edad: ["Junior (Sub-19)", "Senior"],
      genero: ["Masculino", "Femenino", "Mixto (relay)"],
    },
  },
  {
    id: 33,
    nombre: "Remo",
    nombreIngles: "Rowing",
    slug: "remo",
    federacion: "World Rowing Federation",
    acronimo: "FISA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: [
        "Single scull (1x)",
        "Double scull (2x)",
        "Quadruple scull (4x)",
        "Pair (2-)",
        "Four (4-)",
        "Eight (8+)",
        "Lightweight double scull (2x LW)",
        "Coxless pair (2- LW)",
      ],
      distancias: ["2000m (estándar)", "1000m (Junior)", "500m (Sprint)", "Remo costero"],
      categorias_edad: ["Sub-19 (Junior)", "Sub-23 (U23)", "Senior", "Masters (27+, 43+, 50+, 55+, 60+, 65+, 70+)"],
      genero: ["Masculino", "Femenino", "Mixto (coxed four mixto)"],
    },
  },
  {
    id: 34,
    nombre: "Rugby 7",
    nombreIngles: "Rugby Sevens",
    slug: "rugby_7",
    federacion: "World Rugby",
    acronimo: "WR",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Rugby 7 (7 jugadores)", "Rugby 15 (no olímpico)", "Rugby League", "Touch Rugby", "Flag Rugby"],
      categorias_edad: ["Sub-18 (Junior)", "Sub-20 (U20)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 35,
    nombre: "Vela",
    nombreIngles: "Sailing",
    slug: "vela",
    federacion: "World Sailing",
    acronimo: "WS",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      clases_olimpicas: ["Dinghy (ILCA 6, ILCA 7)", "Skiff (49er, 49erFX)", "Windsurfer (iQFOiL)", "Nacra 17 (Catamarán mixto)", "470 mixto"],
      clases_no_olimpicas: ["Optimist", "Laser Radial", "Sunfish", "420", "Snipe", "Finn", "Star", "Soling", "Offshore (Volvo Ocean Race)"],
      categorias_edad: ["Sub-16", "Sub-19 (Youth)", "U21", "Senior", "Masters"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 36,
    nombre: "Tiro Deportivo",
    nombreIngles: "Shooting",
    slug: "tiro_deportivo",
    federacion: "International Shooting Sport Federation",
    acronimo: "ISSF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades_rifle: ["10m aire (carabina)", "50m 3x40 (carabina)", "50m 60 disparos (carabina)", "10m aire mixto"],
      modalidades_pistola: ["10m aire (pistola)", "25m pistola rápida (H)", "25m pistola fuego (M)", "10m aire mixto pistola"],
      modalidades_escopeta: ["Foso olímpico (Trap)", "Foso doble (Double Trap)", "Plato (Skeet)", "Trap mixto", "Skeet mixto"],
      categorias_edad: ["Sub-21 (Junior)", "Senior", "Masters"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 37,
    nombre: "Skateboarding",
    nombreIngles: "Skateboarding",
    slug: "skateboarding",
    federacion: "World Skate",
    acronimo: "WS",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Street (callejero)", "Park (parque)", "Vert (vertical)", "Bowl", "Downhill", "Slalom"],
      categorias_edad: ["Sub-14", "Sub-18 (Junior)", "Open/Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 38,
    nombre: "Escalada Deportiva",
    nombreIngles: "Sport Climbing",
    slug: "escalada_deportiva",
    federacion: "International Federation of Sport Climbing",
    acronimo: "IFSC",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Velocidad (Speed)", "Bloque (Bouldering)", "Dificultad (Lead)", "Combinado"],
      categorias_edad: ["Sub-16 (Youth B)", "Sub-18 (Youth A)", "Sub-20 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 39,
    nombre: "Surf",
    nombreIngles: "Surfing",
    slug: "surf",
    federacion: "International Surfing Association",
    acronimo: "ISA",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Shortboard", "Longboard", "SUP (Stand Up Paddle)", "Bodyboard", "Bodysurf"],
      categorias_edad: ["Sub-16 (Juniors)", "Sub-18", "Open/Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 40,
    nombre: "Tenis de Mesa",
    nombreIngles: "Table Tennis",
    slug: "tenis_de_mesa",
    federacion: "International Table Tennis Federation",
    acronimo: "ITTF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Singles masculino", "Singles femenino", "Dobles masculino", "Dobles femenino", "Dobles mixto", "Por equipos"],
      categorias_edad: ["Sub-13", "Sub-15", "Sub-19 (Junior)", "Sub-21 (U21)", "Senior", "Veterans (40+, 50+, 60+, 70+, 80+)"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 41,
    nombre: "Taekwondo",
    nombreIngles: "Taekwondo",
    slug: "taekwondo",
    federacion: "World Taekwondo",
    acronimo: "WT",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      kyorugi_masculino: [
        "-54kg (Fin)",
        "-58kg (Mosca)",
        "-63kg (Gallo)",
        "-68kg (Pluma)",
        "-74kg (Ligero)",
        "-80kg (Welter)",
        "-87kg (Medio)",
        "+87kg (Pesado)",
      ],
      kyorugi_femenino: [
        "-46kg (Fin)",
        "-49kg (Mosca)",
        "-53kg (Gallo)",
        "-57kg (Pluma)",
        "-62kg (Ligero)",
        "-67kg (Welter)",
        "-73kg (Medio)",
        "+73kg (Pesado)",
      ],
      poomsae: [
        "Individual masculino",
        "Individual femenino",
        "Pares",
        "Equipo (3)",
        "Freeestyle individual M",
        "Freestyle individual F",
        "Freestyle pares",
        "Freestyle equipo",
      ],
      categorias_edad: ["Sub-14 (Cadet)", "Sub-17 (Junior)", "Sub-30 (Under 30)", "Senior (+14)", "Masters (17-30, 31-40, 41-50, 51-60, 61+)"],
      genero: ["Masculino", "Femenino", "Mixto (pares poomsae)"],
    },
  },
  {
    id: 42,
    nombre: "Tenis",
    nombreIngles: "Tennis",
    slug: "tenis",
    federacion: "International Tennis Federation",
    acronimo: "ITF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Singles masculino", "Singles femenino", "Dobles masculino", "Dobles femenino", "Dobles mixto"],
      superficies: ["Tierra batida (Clay)", "Hierba (Grass)", "Pista dura (Hard court)", "Alfombra (Carpet - descontinuada)"],
      categorias_edad: ["Sub-10", "Sub-12", "Sub-14", "Sub-16", "Sub-18 (Junior)", "Senior (ATP/WTA)", "Senior (45+, 55+, 65+, 75+)"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 43,
    nombre: "Triatlón",
    nombreIngles: "Triathlon",
    slug: "triatlon",
    federacion: "World Triathlon",
    acronimo: "WT",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      distancias: [
        "Sprint (750m nat + 20km bici + 5km carrera)",
        "Olímpico (1.5km + 40km + 10km)",
        "70.3 (Half-Ironman: 1.9km + 90km + 21km)",
        "Ironman (3.8km + 180km + 42.2km)",
        "Super Sprint",
        "Duatlón",
        "Acuatlón",
        "Triatló de invierno",
      ],
      modalidades: ["Individual", "Relevo mixto por equipos"],
      categorias_edad: ["Youth (15-19)", "Junior (20-23)", "Elite/Senior", "Age Group (25-29, 30-34, ..., 80-84, 85+)"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 44,
    nombre: "Voleibol",
    nombreIngles: "Volleyball",
    slug: "voleibol",
    federacion: "Fédération Internationale de Volleyball",
    acronimo: "FIVB",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Voleibol indoor (6v6)", "Voleibol playa (2v2)", "Snow volleyball", "Sitting volleyball (Paralímpico)"],
      categorias_edad: ["Sub-19 (Junior World Championship)", "Sub-21 (Norceca)", "Sub-23", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 45,
    nombre: "Halterofilia",
    nombreIngles: "Weightlifting",
    slug: "halterofilia",
    federacion: "International Weightlifting Federation",
    acronimo: "IWF",
    estadoOlimpico: "Olímpico de Verano",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      levantamientos: ["Arranque (Snatch)", "Dos tiempos (Clean & Jerk)", "Total"],
      categorias_peso_masculino: ["-55kg", "-61kg", "-67kg", "-73kg", "-81kg", "-89kg", "-96kg", "-102kg", "-109kg", "+109kg"],
      categorias_peso_femenino: ["-45kg", "-49kg", "-55kg", "-59kg", "-64kg", "-71kg", "-76kg", "-81kg", "-87kg", "+87kg"],
      categorias_edad: [
        "Sub-17 (Youth)",
        "Sub-20 (Junior)",
        "Senior",
        "Masters (35-39, 40-44, 45-49, 50-54, 55-59, 60-64, 65-69, 70-74, 75-79, 80+)",
      ],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 61,
    nombre: "Béisbol / Sóftbol",
    nombreIngles: "Baseball / Softball",
    slug: "beisbol_softbol",
    federacion: "World Baseball Softball Confederation",
    acronimo: "WBSC",
    estadoOlimpico: "Olímpico LA2028 (aprobado)",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades_beisbol: ["9 entradas (estándar)", "7 entradas (amateur/youth)", "Béisbol 5 (urbano)"],
      modalidades_softball: ["Softball femenino (pitcheo rápido)", "Softball masculino (pitcheo lento)", "Softball 5"],
      categorias_edad: ["Sub-12", "Sub-15", "Sub-18 (Juvenil)", "Sub-21 (Junior)", "Sub-23", "Senior"],
      genero: ["Masculino (béisbol)", "Femenino (sóftbol)", "Mixto (béisbol 5)"],
    },
  },
  {
    id: 63,
    nombre: "Flag Football",
    nombreIngles: "Flag Football",
    slug: "flag_football",
    federacion: "International Federation of American Football",
    acronimo: "IFAF",
    estadoOlimpico: "Olímpico LA2028 (aprobado)",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["5v5 (estándar)", "4v4", "7v7"],
      categorias_edad: ["Sub-14", "Sub-18 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 65,
    nombre: "Squash",
    nombreIngles: "Squash",
    slug: "squash",
    federacion: "World Squash Federation",
    acronimo: "WSF",
    estadoOlimpico: "Olímpico LA2028 (aprobado)",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["Singles masculino", "Singles femenino", "Dobles masculino", "Dobles femenino", "Dobles mixto"],
      categorias_edad: ["Sub-15 (Juvenil)", "Sub-19 (Junior)", "Sub-23 (U23)", "Senior", "Masters (35+, 45+, 55+, 65+)"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 66,
    nombre: "Automovilismo",
    nombreIngles: "Motorsport",
    slug: "automovilismo",
    federacion: "Fédération Internationale de l'Automobile",
    acronimo: "FIA",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: [
        "Formula 1",
        "Formula E",
        "Formula 2",
        "Formula 3",
        "IndyCar",
        "NASCAR",
        "Rally (WRC)",
        "Dakar Rally",
        "GT3/GT4",
        "Endurance (WEC/Le Mans)",
        "Karting",
        "Drift",
      ],
      categorias_edad: ["Karting (Sub-8 a 18)", "F4 (Sub-18)", "F3/F2 (18-25)", "Elite/Senior"],
      genero: ["Mixto"],
    },
  },
  {
    id: 67,
    nombre: "Ajedrez",
    nombreIngles: "Chess",
    slug: "ajedrez",
    federacion: "FIDE",
    acronimo: "FIDE",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      formatos: ["Clásico", "Rápido (Rapid)", "Blitz", "Bullet", "960 (Fischer Random)"],
      modalidades: ["Individual", "Por equipos (Olimpiada)", "Correspondencia"],
      categorias_edad: ["Sub-8", "Sub-10", "Sub-12", "Sub-14", "Sub-16", "Sub-18 (Junior)", "Senior", "Senior (50+)"],
      genero: ["Abierto/Masculino", "Femenino"],
    },
  },
  {
    id: 68,
    nombre: "Bolos (Bowling)",
    nombreIngles: "Bowling",
    slug: "bolos_bowling",
    federacion: "World Bowling",
    acronimo: "WB",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: ["Ten-pin (10 pinos)", "Nine-pin (9 pinos)", "Duckpin", "Candlepin", "5-pin"],
      formatos: ["Singles", "Dobles", "Trios", "Cuartetos", "Quintetos", "Masters"],
      categorias_edad: ["Sub-15 (Juvenil)", "Sub-21 (Junior)", "Senior", "Senior (50+, 60+)"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 69,
    nombre: "Billar",
    nombreIngles: "Billiards / Cue Sports",
    slug: "billar",
    federacion: "World Billiards Sport Federation",
    acronimo: "WBSF",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: ["Carom (libre, 3 bandas, cadete)", "Pool (8-ball, 9-ball, 10-ball, 14.1 continuo)", "Snooker", "English billiards"],
      categorias_edad: ["Sub-21 (Junior)", "Senior", "Senior (40+, 50+)"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 71,
    nombre: "Pelota Vasca",
    nombreIngles: "Basque Pelota",
    slug: "pelota_vasca",
    federacion: "Federación Internacional de Pelota Vasca",
    acronimo: "FIPV",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: ["Cesta punta (Jai alai)", "Pelota a mano", "Pala", "Paleta goma", "Frontón", "Remonte", "Xare"],
      categorias_edad: ["Alevín", "Infantil", "Juvenil", "Sub-23", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 72,
    nombre: "Motociclismo",
    nombreIngles: "Motorcycling",
    slug: "motociclismo",
    federacion: "Fédération Internationale de Motocyclisme",
    acronimo: "FIM",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: [
        "MotoGP (Moto1, Moto2, Moto3)",
        "Superbike (WSBK)",
        "Enduro",
        "Motocross (MXGP, MX2)",
        "Trial",
        "Speedway",
        "Flat track",
        "Hill climb",
        "Sidecar",
      ],
      categorias_edad: ["Sub-16 (Juniors)", "Sub-18", "Elite/Senior"],
      genero: ["Masculino", "Femenino (en expansión)"],
    },
  },
  {
    id: 75,
    nombre: "Karate",
    nombreIngles: "Karate",
    slug: "karate",
    federacion: "World Karate Federation",
    acronimo: "WKF",
    estadoOlimpico: "Fue Olímpico en Tokyo 2020 - No en LA2028",
    categoriaGlobal: "artes_marciales_y_combate",
    categoriasCompetencia: {
      kumite_masculino: ["-60kg", "-67kg", "-75kg", "-84kg", "+84kg"],
      kumite_femenino: ["-50kg", "-55kg", "-61kg", "-68kg", "+68kg"],
      kata: ["Kata masculino individual", "Kata femenino individual", "Kata por equipos masculino", "Kata por equipos femenino"],
      categorias_edad: ["Sub-14 (Cadetes)", "Sub-21 (Junior)", "Senior", "Veteran (35+, 45+, 55+, 65+)"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 76,
    nombre: "Muay Thai",
    nombreIngles: "Muay Thai",
    slug: "muay_thai",
    federacion: "World Muaythai Federation / IFMA",
    acronimo: "WMF/IFMA",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      categorias_peso_masculino: ["-51kg", "-54kg", "-57kg", "-60kg", "-63.5kg", "-67kg", "-71kg", "-75kg", "-81kg", "-86kg", "-91kg", "+91kg"],
      categorias_peso_femenino: ["-48kg", "-51kg", "-54kg", "-57kg", "-60kg", "-63.5kg", "-67kg", "-71kg", "-75kg", "+75kg"],
      modalidades: ["Amateur (A-Class)", "Semiprofesional", "Profesional"],
      categorias_edad: ["Micro (Sub-8)", "Sub-10", "Sub-12", "Sub-14 (Cadet)", "Sub-18 (Youth)", "Sub-21 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 77,
    nombre: "Kickboxing",
    nombreIngles: "Kickboxing",
    slug: "kickboxing",
    federacion: "World Association of Kickboxing Organizations",
    acronimo: "WAKO",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: ["Full Contact", "Low Kick", "K1 Rules", "Light Contact", "Semi Contact", "Musical Forms", "Kick Light", "Pointfighting"],
      categorias_peso: ["-52kg", "-56kg", "-60kg", "-65kg", "-70kg", "-74kg", "-79kg", "-84kg", "-89kg", "+89kg (varía por modalidad)"],
      categorias_edad: ["Sub-14 (Cadet)", "Sub-18 (Junior)", "Sub-21 (U21)", "Senior", "Veterans"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 79,
    nombre: "Wushu / Kung Fu",
    nombreIngles: "Wushu",
    slug: "wushu_kung_fu",
    federacion: "International Wushu Federation",
    acronimo: "IWUF",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: [
        "Taolu (formas/katas): Changquan, Nanquan, Taijiquan, Jianshu, Daoshu, Gunshu, Qiangshu, Nandao, Nangun",
        "Sanda/Sanshou (combate)",
      ],
      categorias_peso_sanda_masculino: ["-48kg", "-52kg", "-56kg", "-60kg", "-65kg", "-70kg", "-75kg", "-80kg", "-85kg", "+85kg"],
      categorias_peso_sanda_femenino: ["-48kg", "-52kg", "-56kg", "-60kg", "-65kg", "+65kg"],
      categorias_edad: ["Sub-14 (Juvenil)", "Sub-18 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 80,
    nombre: "Ju-Jitsu",
    nombreIngles: "Ju-Jitsu",
    slug: "ju_jitsu",
    federacion: "Ju-Jitsu International Federation",
    acronimo: "JJIF",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: ["Ne-waza (grappling)", "Fighting system (combate)", "Duo system (kata en pareja)"],
      categorias_peso: ["-55kg", "-62kg", "-69kg", "-77kg", "-85kg", "-94kg", "+94kg (varía por modalidad)"],
      categorias_edad: ["Sub-15 (Youth)", "Sub-18 (Cadet)", "Sub-21 (Junior)", "Senior", "Masters"],
      genero: ["Masculino", "Femenino", "Mixto (duo)"],
    },
  },
  {
    id: 82,
    nombre: "Lucha Olímpica (Grappling)",
    nombreIngles: "Grappling",
    slug: "lucha_olimpica_grappling",
    federacion: "United World Wrestling",
    acronimo: "UWW",
    estadoOlimpico: "No Olímpico - Federado",
    categoriaGlobal: "artes_marciales_y_combate",
    categoriasCompetencia: {
      modalidades: ["Grappling sin kimono (nogi)", "Grappling con kimono"],
      categorias_peso: ["-57kg", "-65kg", "-74kg", "-86kg", "-97kg", "-125kg (varía por organización)"],
      categorias_edad: ["Junior (Sub-20)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 83,
    nombre: "MMA (Artes Marciales Mixtas)",
    nombreIngles: "Mixed Martial Arts",
    slug: "mma_artes_marciales_mixtas",
    federacion: "International Mixed Martial Arts Federation",
    acronimo: "IMMAF",
    estadoOlimpico: "No Olímpico",
    categoriaGlobal: "artes_marciales_y_combate",
    categoriasCompetencia: {
      categorias_peso_masculino: [
        "Fresa (-52.2kg)",
        "Mosca (-56.7kg)",
        "Gallo (-61.2kg)",
        "Pluma (-65.8kg)",
        "Ligero (-70.3kg)",
        "Superligero (-77.1kg)",
        "Welter (-83.9kg)",
        "Superwelter (-83.9kg)",
        "Medio (-83.9kg)",
        "Semipesado (-93kg)",
        "Pesado (-120.2kg)",
        "Superpesado (+120.2kg)",
      ],
      categorias_peso_femenino: [
        "Átomo (-47.6kg)",
        "Fresa (-52.2kg)",
        "Mosca (-56.7kg)",
        "Gallo (-61.2kg)",
        "Pluma (-65.8kg)",
        "Ligero (-70.3kg)",
        "Paja (-52.2kg)",
      ],
      categorias_edad: ["Amateur (Sub-18, Sub-21)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 87,
    nombre: "Pádel",
    nombreIngles: "Padel",
    slug: "padel",
    federacion: "International Padel Federation",
    acronimo: "FIP",
    estadoOlimpico: "No Olímpico",
    categoriaGlobal: "no_olimpicos_federacion_internacional",
    categoriasCompetencia: {
      modalidades: ["Dobles (estándar)", "Singles (menos común)"],
      categorias_edad: [
        "Sub-12 (Benjamín)",
        "Sub-14 (Alevín)",
        "Sub-16 (Infantil)",
        "Sub-18 (Cadete)",
        "Sub-23 (Junior)",
        "Senior",
        "Veteranos (35+, 45+, 55+, 65+)",
      ],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 88,
    nombre: "Ráquetbol",
    nombreIngles: "Racquetball",
    slug: "raquetbol",
    federacion: "International Racquetball Federation",
    acronimo: "IRF",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: ["Singles", "Dobles", "Dobles mixto"],
      categorias_edad: ["Sub-18 (Junior)", "Sub-22 (College)", "Senior", "Senior (40+, 50+, 55+, 60+, 65+, 70+, 75+, 80+)"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 89,
    nombre: "Frontón (Handball Mural)",
    nombreIngles: "Handball (Wall)",
    slug: "fronton_handball_mural",
    federacion: "International Handball Federation (WH)",
    acronimo: "IHF/WH",
    estadoOlimpico: "No Olímpico",
    categoriaGlobal: "no_olimpicos_federacion_internacional",
    categoriasCompetencia: {
      modalidades: ["1v1 (Singles)", "2v2 (Dobles)", "4-Wall", "1-Wall", "3-Wall"],
      categorias_edad: ["Sub-18 (Junior)", "Senior", "Masters (40+, 50+, 60+, 70+)"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 94,
    nombre: "Patinaje de Velocidad en Línea",
    nombreIngles: "Inline Speed Skating",
    slug: "patinaje_de_velocidad_en_linea",
    federacion: "World Skate",
    acronimo: "WS",
    estadoOlimpico: "No Olímpico - Federado",
    categoriaGlobal: "no_olimpicos_federacion_internacional",
    categoriasCompetencia: {
      distancias: [
        "100m",
        "200m",
        "300m (TT)",
        "500m",
        "1000m",
        "1500m",
        "3000m eliminación",
        "5000m",
        "10000m",
        "15000m",
        "20000m",
        "Maratón (42km)",
        "Relevos",
      ],
      superficies: ["Pista (500m)", "Carretera", "Maratón"],
      categorias_edad: ["Sub-13", "Sub-16 (Juvenil)", "Sub-18 (Junior)", "Sub-23 (Promesas)", "Senior", "Masters"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 97,
    nombre: "Fútbol Americano",
    nombreIngles: "American Football",
    slug: "futbol_americano",
    federacion: "International Federation of American Football",
    acronimo: "IFAF",
    estadoOlimpico: "No Olímpico (flag football sí en LA2028)",
    categoriaGlobal: "no_olimpicos_federacion_internacional",
    categoriasCompetencia: {
      modalidades: ["11v11 (estándar)", "9v9", "8v8", "7v7", "Flag Football"],
      categorias_edad: ["Sub-12", "Sub-14", "Sub-17 (Junior)", "Sub-19 (College/University)", "Sub-23", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 101,
    nombre: "Ultimate Frisbee",
    nombreIngles: "Ultimate Frisbee",
    slug: "ultimate_frisbee",
    federacion: "World Flying Disc Federation",
    acronimo: "WFDF",
    estadoOlimpico: "No Olímpico",
    categoriaGlobal: "no_olimpicos_federacion_internacional",
    categoriasCompetencia: {
      modalidades: ["Open (7v7)", "Women (7v7)", "Mixed (7v7 mixto)", "Beach Ultimate (5v5)", "Indoor Ultimate", "Goaltimate"],
      categorias_edad: ["Sub-17 (Youth)", "Sub-20 (U20)", "Sub-24 (U24)", "Senior", "Masters (30+, 40+)"],
      genero: ["Masculino (Open)", "Femenino", "Mixto"],
    },
  },
  {
    id: 103,
    nombre: "Polo",
    nombreIngles: "Polo",
    slug: "polo",
    federacion: "Federation of International Polo",
    acronimo: "FIP",
    estadoOlimpico: "Reconocido COI - No Olímpico",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      modalidades: ["Grass polo (4v4)", "Arena polo (3v3)", "Snow polo", "Elephant polo (no oficial)"],
      handicap: ["-2 a +10 goles (sistema de hándicap)"],
      categorias_edad: ["Junior (Sub-18)", "Sub-25 (U25)", "Senior"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 106,
    nombre: "Deportes Electrónicos (Esports)",
    nombreIngles: "Esports",
    slug: "deportes_electronicos_esports",
    federacion: "Global Esports Federation",
    acronimo: "GEF",
    estadoOlimpico: "Olímpicos Esports 2025 (primera edición autónoma)",
    categoriaGlobal: "deportes_mentales_y_estrategia",
    categoriasCompetencia: {
      juegos_olimpicos_esports_2025: [
        "Archery (tiro con arco simulado)",
        "Baseball (béisbol simulado)",
        "Chess (ajedrez online)",
        "Cycling (ciclismo simulado)",
        "Dance (dance game)",
        "Formula E Racing (automovilismo simulado)",
        "Mobile Legends: Bang Bang (MOBA)",
        "Sailing (vela simulada)",
        "Street Fighter 6 (juego de lucha)",
        "Tennis (tenis simulado)",
      ],
      generos_esports: ["Battle Royale", "MOBA", "FPS", "RTS", "Sports simulation", "Fighting games", "Racing"],
      categorias_edad: ["Sub-18", "Open/Senior"],
      genero: ["Mixto (en su mayoría)"],
    },
  },
  {
    id: 107,
    nombre: "Atletismo Paralímpico",
    nombreIngles: "Para Athletics",
    slug: "atletismo_paralimpico",
    federacion: "World Para Athletics",
    acronimo: "WPA",
    estadoOlimpico: "Paralímpico",
    categoriaGlobal: "paralimpicos",
    categoriasCompetencia: {
      clases_funcionamiento: [
        "T11-T13 (visual)",
        "T20 (intelectual)",
        "T31-T38 (cerebral)",
        "T40-T41 (estatura baja)",
        "T42-T47 (amputados/miembros)",
        "T51-T54 (silla de ruedas)",
        "T61-T64 (prótesis)",
      ],
      pruebas: ["100m-1500m pista", "5000m-10000m (clases en silla)", "Maratón", "Salto de longitud", "Lanzamientos"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 108,
    nombre: "Natación Paralímpica",
    nombreIngles: "Para Swimming",
    slug: "natacion_paralimpica",
    federacion: "World Para Swimming (World Aquatics)",
    acronimo: "WPS",
    estadoOlimpico: "Paralímpico",
    categoriaGlobal: "paralimpicos",
    categoriasCompetencia: {
      clases: ["S1-S14 (estilo libre/espalda/mariposa)", "SB1-SB14 (pecho)", "SM1-SM14 (combinado)"],
      clasificacion: ["S1-S10: discapacidades físicas", "S11-S13: discapacidades visuales", "S14: discapacidades intelectuales"],
      distancias: ["50m", "100m", "200m", "400m", "800m", "1500m", "Relevos"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 109,
    nombre: "Boccia",
    nombreIngles: "Boccia",
    slug: "boccia",
    federacion: "Boccia International Sports Federation",
    acronimo: "BISFed",
    estadoOlimpico: "Paralímpico",
    categoriaGlobal: "paralimpicos",
    categoriasCompetencia: {
      clases: [
        "BC1 (parálisis cerebral/uso brazo asistido)",
        "BC2 (parálisis cerebral leve)",
        "BC3 (severa discapacidad - usa rampa)",
        "BC4 (otras discapacidades no cerebrales)",
      ],
      modalidades: ["Individual", "Parejas (BC3)", "Equipos (BC1/BC2)"],
      genero: ["Mixto"],
    },
  },
  {
    id: 110,
    nombre: "Goalball",
    nombreIngles: "Goalball",
    slug: "goalball",
    federacion: "International Blind Sports Federation",
    acronimo: "IBSA",
    estadoOlimpico: "Paralímpico",
    categoriaGlobal: "paralimpicos",
    categoriasCompetencia: {
      modalidades: ["3v3 (estándar)"],
      clasificacion: ["B1-B3 (todos los atletas llevan antifaz)"],
      categorias_edad: ["Sub-16 (Youth)", "Sub-20 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 111,
    nombre: "Tenis en Silla de Ruedas",
    nombreIngles: "Wheelchair Tennis",
    slug: "tenis_en_silla_de_ruedas",
    federacion: "International Tennis Federation (WTF)",
    acronimo: "ITF",
    estadoOlimpico: "Paralímpico",
    categoriaGlobal: "paralimpicos",
    categoriasCompetencia: {
      clases: ["Open (discapacidad en piernas)", "Quad (discapacidad en brazos y piernas)"],
      modalidades: ["Singles", "Dobles"],
      categorias_edad: ["Junior (Sub-18)", "Senior"],
      genero: ["Masculino", "Femenino", "Mixto (dobles)"],
    },
  },
  {
    id: 112,
    nombre: "Baloncesto en Silla de Ruedas",
    nombreIngles: "Wheelchair Basketball",
    slug: "baloncesto_en_silla_de_ruedas",
    federacion: "International Wheelchair Basketball Federation",
    acronimo: "IWBF",
    estadoOlimpico: "Paralímpico",
    categoriaGlobal: "paralimpicos",
    categoriasCompetencia: {
      sistema_puntos: ["Clasificación funcional 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5 (máx 14 pts por 5 jugadores en cancha)"],
      modalidades: ["5v5"],
      categorias_edad: ["Sub-23 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 113,
    nombre: "Breakdance (Breaking)",
    nombreIngles: "Breaking / B-boying",
    slug: "breakdance_breaking",
    federacion: "World DanceSport Federation",
    acronimo: "WDSF",
    estadoOlimpico: "Olímpico en Paris 2024 - No en LA2028",
    categoriaGlobal: "olimpicos_verano",
    categoriasCompetencia: {
      modalidades: ["1v1 Battle", "Crew Battle (equipos)", "Cypher (eliminatorias)"],
      categorias_edad: ["Youth (Sub-18)", "Senior"],
      genero: ["B-boys (masculino)", "B-girls (femenino)"],
    },
  },
  {
    id: 114,
    nombre: "Parkour / Freerunning",
    nombreIngles: "Parkour",
    slug: "parkour_freerunning",
    federacion: "International Gymnastics Federation (FIG)",
    acronimo: "FIG",
    estadoOlimpico: "No Olímpico",
    categoriaGlobal: "no_olimpicos_federacion_internacional",
    categoriasCompetencia: {
      modalidades: ["Speed run (velocidad)", "Freestyle/Freerunning (creatividad)", "Street", "Competition parcours"],
      categorias_edad: ["Sub-16 (Youth)", "Sub-18 (Junior)", "Senior"],
      genero: ["Masculino", "Femenino"],
    },
  },
  {
    id: 115,
    nombre: "Acrobacias / Cheerleading / Tumbling",
    nombreIngles: "Acrobatic Sports",
    slug: "acrobacias_cheerleading_tumbling",
    federacion: "Fédération Internationale de Gymnastique",
    acronimo: "FIG",
    estadoOlimpico: "No Olímpico",
    categoriaGlobal: "no_olimpicos_federacion_internacional",
    categoriasCompetencia: {
      modalidades: [
        "Acrobática gimnasia (parejas M, parejas F, parejas mixtas, tríos F, cuartetos M)",
        "Cheerleading (Stunt, Pyramid)",
        "Acrobacias en telas aéreas",
        "Cyr wheel (rueda)",
      ],
      categorias_edad: ["Age Groups (Sub-16, Sub-19)", "Senior"],
      genero: ["Masculino", "Femenino", "Mixto"],
    },
  },
  {
    id: 121,
    nombre: "Cheerleading All Stars",
    nombreIngles: "All Star Cheerleading",
    slug: "cheerleading_all_stars",
    federacion: "International Cheer Union / ICU",
    acronimo: "ICU",
    estadoOlimpico: "No Olímpico - Reconocido COI",
    categoriaGlobal: "reconocidos_COI_no_olimpicos",
    categoriasCompetencia: {
      CHEER_ALL_STAR_NOVICE: {
        "descripcion": "Categorías para equipos novatos",
        "niveles": [
          { "nivel": 1, "categorias": [{ "categoria": "Tiny", "rama": "Única", "edad": "5 a 6 años", "anio_nacimiento": "2019 – 2021", "integrantes": "10 a 30" }, { "categoria": "Mini", "rama": "Única", "edad": "5 a 8 años", "anio_nacimiento": "2017 – 2021", "integrantes": "10 a 30" }, { "categoria": "Youth", "rama": "Única", "edad": "8 a 12 años", "anio_nacimiento": "2013 – 2018", "integrantes": "10 a 30" }, { "categoria": "Junior", "rama": "Única", "edad": "12 a 16 años", "anio_nacimiento": "2009 – 2014", "integrantes": "10 a 30" }] },
        ],
      },
      CHEER_ALL_STAR_PREP: {
        "descripcion": "Categorías para equipos preparatorios",
        "niveles": [
          { "nivel": "1.1", "categorias": [{ "categoria": "Tiny", "rama": "Única", "edad": "5 a 6 años", "anio_nacimiento": "2019 – 2021", "integrantes": "10 a 30" }, { "categoria": "Mini", "rama": "Única", "edad": "5 a 8 años", "anio_nacimiento": "2017 – 2021", "integrantes": "10 a 30" }, { "categoria": "Youth", "rama": "Única", "edad": "8 a 12 años", "anio_nacimiento": "2013 – 2018", "integrantes": "10 a 30" }, { "categoria": "Junior", "rama": "Única", "edad": "12 a 16 años", "anio_nacimiento": "2009 – 2014", "integrantes": "10 a 30" }, { "categoria": "Senior", "rama": "Única", "edad": "14 a 18 años", "anio_nacimiento": "2007 – 2012", "integrantes": "10 a 30" }, { "categoria": "Open", "rama": "Única", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 30" }] },
          { "nivel": "2.1", "categorias": [{ "categoria": "Youth", "rama": "Única", "edad": "8 a 12 años", "anio_nacimiento": "2013 – 2018", "integrantes": "10 a 30" }, { "categoria": "Junior", "rama": "Única", "edad": "12 a 16 años", "anio_nacimiento": "2009 – 2014", "integrantes": "10 a 30" }, { "categoria": "Senior", "rama": "Única", "edad": "14 a 18 años", "anio_nacimiento": "2007 – 2012", "integrantes": "10 a 30" }, { "categoria": "Open", "rama": "Única", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 30" }] },
          { "nivel": "2.2", "categorias": [{ "categoria": "Junior", "rama": "Única", "edad": "12 a 16 años", "anio_nacimiento": "2009 – 2014", "integrantes": "10 a 30" }, { "categoria": "Senior", "rama": "Única", "edad": "14 a 18 años", "anio_nacimiento": "2007 – 2012", "integrantes": "10 a 30" }, { "categoria": "Open", "rama": "Única", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 30" }] },
        ],
      },
      CHEER_ALL_STAR_ELITE: {
        "descripcion": "Categorías para equipos avanzados",
        "niveles": [
          { "nivel": 1, "categorias": [{ "categoria": "Tiny", "rama": "Única", "edad": "5 a 6 años", "anio_nacimiento": "2019 – 2021", "integrantes": "10 a 30" }, { "categoria": "Mini", "rama": "Única", "edad": "5 a 8 años", "anio_nacimiento": "2017 – 2021", "integrantes": "10 a 30" }, { "categoria": "Youth", "rama": "Femenino/Mixto", "edad": "8 a 12 años", "anio_nacimiento": "2013 – 2018", "integrantes": "10 a 30" }, { "categoria": "Junior", "rama": "Femenino/Mixto", "edad": "12 a 16 años", "anio_nacimiento": "2009 – 2014", "integrantes": "10 a 30" }, { "categoria": "Senior", "rama": "Femenino/Mixto", "edad": "14 a 18 años", "anio_nacimiento": "2007 – 2012", "integrantes": "10 a 30" }] },
          { "nivel": 2, "categorias": [{ "categoria": "Youth", "rama": "Única", "edad": "8 a 12 años", "anio_nacimiento": "2013 – 2018", "integrantes": "10 a 30" }, { "categoria": "Junior", "rama": "Femenino/Mixto", "edad": "12 a 16 años", "anio_nacimiento": "2009 – 2014", "integrantes": "10 a 30" }, { "categoria": "Senior", "rama": "Femenino/Mixto", "edad": "14 a 18 años", "anio_nacimiento": "2007 – 2012", "integrantes": "10 a 30" }, { "categoria": "Open", "rama": "Femenino/Mixto", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 30" }] },
          { "nivel": 3, "categorias": [{ "categoria": "Youth", "rama": "Única", "edad": "8 a 12 años", "anio_nacimiento": "2013 – 2018", "integrantes": "10 a 30" }, { "categoria": "Junior", "rama": "Única", "edad": "12 a 16 años", "anio_nacimiento": "2009 – 2014", "integrantes": "10 a 30" }, { "categoria": "Senior", "rama": "Femenino/Mixto", "edad": "14 a 18 años", "anio_nacimiento": "2007 – 2012", "integrantes": "10 a 30" }, { "categoria": "Open", "rama": "Femenino/Mixto", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 30" }] },
          { "nivel": "4.2", "categorias": [{ "categoria": "Open", "rama": "Femenino/Mixto", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 30" }] },
          { "nivel": 4, "categorias": [{ "categoria": "Senior", "rama": "Única", "edad": "14 a 18 años", "anio_nacimiento": "2007 – 2012", "integrantes": "10 a 30" }, { "categoria": "Open", "rama": "Femenino", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 30" }, { "categoria": "Open", "rama": "Mixto Medium (Max 8 hombres)", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 24" }, { "categoria": "Open", "rama": "Mixto Large (Min 9 hombres)", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "12 a 30" }] },
        ],
      },
      CHEER_ALL_STAR_IASF_WORLDS: {
        "descripcion": "Categorías para equipos que compiten por BID para IASF WORLDS",
        "niveles": [
          { "nivel": 5, "categorias": [{ "categoria": "Senior", "rama": "Femenino/Mixto", "edad": "13 a 17 años", "anio_nacimiento": "2008 – 2013", "integrantes": "10 a 24" }, { "categoria": "Open", "rama": "Femenino/Mixto", "edad": "15 años +", "anio_nacimiento": "Hasta 2011", "integrantes": "10 a 24" }] },
          { "nivel": 6, "categorias": [{ "categoria": "Open", "rama": "Mixto", "edad": "15 años +", "anio_nacimiento": "Hasta 2011", "integrantes": "10 a 24" }] },
          { "nivel": 7, "categorias": [{ "categoria": "Open", "rama": "Mixto", "edad": "16 años +", "anio_nacimiento": "Hasta 2010", "integrantes": "10 a 24" }] },
        ],
      },
      CHEER_ALL_STAR_ADAPTADO: {
        "descripcion": "Habilidades Especiales - Categoría para deportistas en condición de discapacidad",
        "requisito": "El equipo debe contar con al menos 50% de deportistas con discapacidad intelectual en combinación con otros deportistas diagnosticados con otras condiciones.",
        "condiciones_diagnosticadas": [
          "Potencia muscular deteriorada",
          "Rango de movimiento deteriorado",
          "Ausencia de extremidades",
          "Diferencia en longitud de las piernas",
          "Baja estatura",
          "Hipertonía",
          "Atetosis",
          "Impedimento Visual",
          "Impedimento Intelectual",
          "Impedimento Auditivo",
        ],
        "reglamento": "ICU 2026 para Special Olympics Unified NOVICE",
        "niveles": [
          { "nivel": 1, "categorias": [{ "categoria": "Habs. Especiales", "rama": "Única", "edad": "8 años +", "anio_nacimiento": "Hasta 2018", "integrantes": "10 a 24" }] },
        ],
      },
    },
  },
  {
    id: 122,
    nombre: 'Entrenamiento Funcional',
    nombreIngles: 'Functional Training',
    slug: 'entrenamiento_funcional',
    federacion: 'Federaciones Nacionales de Fitness',
    acronimo: 'FT',
    estadoOlimpico: 'No Olímpico',
    categoriaGlobal: 'no_olimpicos_federacion_internacional' as CategoriaGlobal,
    categoriasCompetencia: {
      genero: ['Masculino', 'Femenino', 'Mixto'],
      categorias_edad: ['Sub-16', 'Sub-18', 'Adulto', 'Masters 35+', 'Masters 40+', 'Masters 50+'],
      niveles: ['Principiante', 'Intermedio', 'Avanzado', 'Élite'],
      modalidades: ['Individual', 'Parejas', 'Equipos'],
    },
  },
  {
    id: 123,
    nombre: 'CrossFit',
    nombreIngles: 'CrossFit',
    slug: 'crossfit',
    federacion: 'CrossFit LLC / IFSO',
    acronimo: 'CF',
    estadoOlimpico: 'No Olímpico',
    categoriaGlobal: 'no_olimpicos_federacion_internacional' as CategoriaGlobal,
    categoriasCompetencia: {
      genero: ['Masculino', 'Femenino', 'Mixto'],
      categorias_edad: ['Teen 14-15', 'Teen 16-17', 'Individual 18-34', 'Masters 35-39', 'Masters 40-44', 'Masters 45-49', 'Masters 50-54', 'Masters 55-59', 'Masters 60+'],
      divisiones: ['Scaled', 'RX', 'Élite'],
      modalidades: ['Individual', 'Parejas', 'Equipos (4 personas)'],
    },
  },
  {
    id: 124,
    nombre: 'Cross Training',
    nombreIngles: 'Cross Training',
    slug: 'cross_training',
    federacion: 'Federaciones Nacionales de Fitness',
    acronimo: 'CT',
    estadoOlimpico: 'No Olímpico',
    categoriaGlobal: 'no_olimpicos_federacion_internacional' as CategoriaGlobal,
    categoriasCompetencia: {
      genero: ['Masculino', 'Femenino', 'Mixto'],
      categorias_edad: ['Sub-16', 'Sub-18', 'Adulto', 'Masters 35+', 'Masters 40+', 'Masters 50+'],
      niveles: ['Principiante', 'Intermedio', 'Avanzado', 'Competitivo'],
      modalidades: ['Individual', 'Parejas', 'Equipos'],
    },
  },
  {
    id: 125,
    nombre: 'Lucha',
    nombreIngles: 'Wrestling',
    slug: 'lucha',
    federacion: 'United World Wrestling (UWW)',
    acronimo: 'UWW',
    estadoOlimpico: 'Olímpico',
    categoriaGlobal: 'artes_marciales_y_combate' as CategoriaGlobal,
    categoriasCompetencia: {
      genero: ['Masculino', 'Femenino'],
      categorias_edad: ['Escolar', 'Cadetes U15', 'Cadetes U17', 'Junior U20', 'U23', 'Senior'],
      categorias_peso_masculino: ['57 kg', '65 kg', '74 kg', '86 kg', '97 kg', '125 kg'],
      categorias_peso_femenino: ['50 kg', '53 kg', '57 kg', '62 kg', '68 kg', '76 kg'],
      estilos: ['Libre', 'Grecorromana', 'Femenina'],
    },
  },
  {
    id: 126,
    nombre: 'Baile',
    nombreIngles: 'Dance',
    slug: 'baile',
    federacion: 'N/A',
    acronimo: 'BAILE',
    estadoOlimpico: 'No Olímpico',
    categoriaGlobal: 'no_olimpicos_federacion_internacional' as CategoriaGlobal,
    categoriasCompetencia: {
      genero: ['Masculino', 'Femenino', 'Mixto'],
      categorias_edad: ['Infantil', 'Juvenil', 'Adulto', 'Senior'],
      estilos: ['Aéreos', 'Urbanos', 'Salón', 'Comercial'],
    },
  },
  {
    id: 127,
    nombre: 'Danza',
    nombreIngles: 'Dance Arts',
    slug: 'danza',
    federacion: 'N/A',
    acronimo: 'DANZA',
    estadoOlimpico: 'No Olímpico',
    categoriaGlobal: 'no_olimpicos_federacion_internacional' as CategoriaGlobal,
    categoriasCompetencia: {
      genero: ['Masculino', 'Femenino', 'Mixto'],
      categorias_edad: ['Iniciación', 'Formativo', 'Profesional'],
      generos: ['Clásica', 'Contemporánea', 'Folclórica', 'Moderna'],
    },
  },
  {
    id: 128,
    nombre: 'Crosstraining',
    nombreIngles: 'Crosstraining',
    slug: 'crosstraining',
    federacion: 'N/A',
    acronimo: 'CT',
    estadoOlimpico: 'No Olímpico',
    categoriaGlobal: 'no_olimpicos_federacion_internacional' as CategoriaGlobal,
    categoriasCompetencia: {
      genero: ['Masculino', 'Femenino', 'Mixto'],
      categorias_edad: ['General', 'Masters'],
      niveles: ['Principiante', 'Intermedio', 'Avanzado'],
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// Helper Functions
// ═══════════════════════════════════════════════════════════════════════════════

export const TOTAL_SPORTS = SPORTS_CATALOG.length;

export const SPORTS_LIST = SPORTS_CATALOG.map(s => s.nombre);

export const SPORTS_SLUGS = SPORTS_CATALOG.map(s => s.slug);

export function getSportBySlug(slug: string): SportCatalogEntry | undefined {
  return SPORTS_CATALOG.find(s => s.slug === slug || s.nombreIngles.toLowerCase().replace(/\s+/g, '_') === slug);
}

export function getSportById(id: number): SportCatalogEntry | undefined {
  return SPORTS_CATALOG.find(s => s.id === id);
}

export function getSportsByCategory(cat: CategoriaGlobal): SportCatalogEntry[] {
  return SPORTS_CATALOG.filter(s => s.categoriaGlobal === cat);
}

export function searchSports(query: string): SportCatalogEntry[] {
  const q = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  return SPORTS_CATALOG.filter(s => {
    const name = s.nombre.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    const nameEn = s.nombreIngles.toLowerCase();
    return name.includes(q) || nameEn.includes(q) || s.slug.includes(q);
  });
}

export function getAgeCategories(slug: string): string[] {
  const sport = getSportBySlug(slug);
  if (!sport) return [];
  return (sport.categoriasCompetencia.categorias_edad as string[]) || [];
}

export function getGenderCategories(slug: string): string[] {
  const sport = getSportBySlug(slug);
  if (!sport) return [];
  return (sport.categoriasCompetencia.genero as string[]) || [];
}
