// Demo schools with real Colombian locations and coordinates
export const demoSchools = [
  {
    id: 'demo-school-1',
    name: 'Academia Fútbol El Campín',
    city: 'Bogotá',
    address: 'Estadio El Campín, Carrera 30 #57-60',
    latitude: 4.6472,
    longitude: -74.0777,
    email: 'info@futbolelcampin.com',
    phone: '+57 601 234 5678',
    description: 'Academia de fútbol de alto rendimiento ubicada en el icónico Estadio El Campín. Formamos campeones desde 1987.',
    sports: ['Fútbol', 'Fútbol Sala'],
    amenities: ['Canchas profesionales', 'Vestuarios', 'Gimnasio', 'Cafetería', 'Parqueadero'],
    rating: 4.8,
    total_reviews: 156,
    verified: true,
    logo_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=200&h=200&fit=crop',
    cover_image_url: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=1200&h=400&fit=crop',
    is_demo: true,
  },
  {
    id: 'demo-school-2',
    name: 'Club Natación Atanasio',
    city: 'Medellín',
    address: 'Estadio Atanasio Girardot, Carrera 70 #48-99',
    latitude: 6.2567,
    longitude: -75.5906,
    email: 'contacto@natacionatanasio.com',
    phone: '+57 604 345 6789',
    description: 'El mejor centro de natación del Valle de Aburrá. Piscinas olímpicas y programas para todas las edades.',
    sports: ['Natación', 'Waterpolo', 'Clavados'],
    amenities: ['Piscina olímpica', 'Piscina de entrenamiento', 'Sauna', 'Spa', 'Cafetería'],
    rating: 4.9,
    total_reviews: 203,
    verified: true,
    logo_url: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=200&h=200&fit=crop',
    cover_image_url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=1200&h=400&fit=crop',
    is_demo: true,
  },
  {
    id: 'demo-school-3',
    name: 'Academia Tenis Cali',
    city: 'Cali',
    address: 'Club Colombia, Avenida 6 Norte #24-00',
    latitude: 3.4516,
    longitude: -76.5320,
    email: 'reservas@teniscali.com',
    phone: '+57 602 456 7890',
    description: 'Centro de formación tenística con canchas de arcilla y superficie dura. Sede de torneos nacionales.',
    sports: ['Tenis', 'Pádel'],
    amenities: ['Canchas de arcilla', 'Canchas duras', 'Pro shop', 'Gimnasio', 'Restaurante'],
    rating: 4.7,
    total_reviews: 89,
    verified: true,
    logo_url: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=200&h=200&fit=crop',
    cover_image_url: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=1200&h=400&fit=crop',
    is_demo: true,
  },
  {
    id: 'demo-school-4',
    name: 'Escuela Baloncesto Caribe',
    city: 'Barranquilla',
    address: 'Coliseo Elías Chegwin, Calle 72 #54-41',
    latitude: 10.9685,
    longitude: -74.7813,
    email: 'info@basquetcaribe.com',
    phone: '+57 605 567 8901',
    description: 'Cuna de talentos del baloncesto colombiano. Programas desde los 5 años hasta formación profesional.',
    sports: ['Baloncesto', 'Baloncesto 3x3'],
    amenities: ['Coliseo cubierto', 'Gimnasio', 'Fisioterapia', 'Tienda deportiva'],
    rating: 4.6,
    total_reviews: 134,
    verified: true,
    logo_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=200&h=200&fit=crop',
    cover_image_url: 'https://images.unsplash.com/photo-1559692048-79a3f837883d?w=1200&h=400&fit=crop',
    is_demo: true,
  },
  {
    id: 'demo-school-5',
    name: 'Academia Artes Marciales Samurai',
    city: 'Bucaramanga',
    address: 'Centro Comercial Cacique, Local 201',
    latitude: 7.1193,
    longitude: -73.1227,
    email: 'dojo@samuraibucaramanga.com',
    phone: '+57 607 678 9012',
    description: 'Dojo tradicional de artes marciales japonesas. Karate, Judo y Taekwondo con maestros certificados internacionalmente.',
    sports: ['Karate', 'Judo', 'Taekwondo'],
    amenities: ['Dojo climatizado', 'Tatami profesional', 'Vestuarios', 'Tienda de uniformes'],
    rating: 4.9,
    total_reviews: 67,
    verified: true,
    logo_url: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=200&h=200&fit=crop',
    cover_image_url: 'https://images.unsplash.com/photo-1564415315949-7a0c4c73aab4?w=1200&h=400&fit=crop',
    is_demo: true,
  },
  {
    id: 'demo-school-6',
    name: 'Club Ciclismo Bogotá',
    city: 'Bogotá',
    address: 'Parque Simón Bolívar, Entrada Norte',
    latitude: 4.6584,
    longitude: -74.0936,
    email: 'contacto@ciclismobogota.com',
    phone: '+57 601 789 0123',
    description: 'Escuela de ciclismo urbano y de montaña. Rutas guiadas los fines de semana y programas de alto rendimiento.',
    sports: ['Ciclismo de Ruta', 'Ciclismo MTB', 'BMX'],
    amenities: ['Taller de bicicletas', 'Alquiler de equipos', 'Rutas programadas', 'Entrenamiento indoor'],
    rating: 4.5,
    total_reviews: 98,
    verified: true,
    logo_url: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=200&h=200&fit=crop',
    cover_image_url: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=1200&h=400&fit=crop',
    is_demo: true,
  },
  {
    id: 'demo-school-7',
    name: 'Gimnasio CrossFit Cartagena',
    city: 'Cartagena',
    address: 'Bocagrande, Carrera 3 #8-45',
    latitude: 10.3997,
    longitude: -75.5144,
    email: 'box@crossfitcartagena.com',
    phone: '+57 605 890 1234',
    description: 'Box de CrossFit con vista al mar. Entrena como los atletas profesionales en el Caribe colombiano.',
    sports: ['CrossFit', 'Levantamiento de pesas', 'Gimnasia'],
    amenities: ['Box climatizado', 'Equipos Rogue', 'Duchas', 'Parking', 'Tienda de suplementos'],
    rating: 4.8,
    total_reviews: 112,
    verified: true,
    logo_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&h=200&fit=crop',
    cover_image_url: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=1200&h=400&fit=crop',
    is_demo: true,
  },
  {
    id: 'demo-school-8',
    name: 'Escuela Voleibol Playa',
    city: 'Santa Marta',
    address: 'Playa El Rodadero, Sector Norte',
    latitude: 11.2027,
    longitude: -74.2271,
    email: 'info@voleyplaya.com',
    phone: '+57 605 901 2345',
    description: 'Aprende voleibol de playa en las mejores arenas del Caribe. Torneos locales y nacionales todo el año.',
    sports: ['Voleibol Playa', 'Voleibol Indoor'],
    amenities: ['Canchas de playa', 'Sombrillas', 'Hidratación gratuita', 'Vestuarios'],
    rating: 4.7,
    total_reviews: 76,
    verified: true,
    logo_url: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=200&h=200&fit=crop',
    cover_image_url: 'https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=1200&h=400&fit=crop',
    is_demo: true,
  },
];

// Demo programs for schools
export const demoPrograms = [
  // El Campín - Fútbol
  {
    id: 'prog-1',
    school_id: 'demo-school-1',
    name: 'Fútbol Infantil (6-11 años)',
    sport: 'Fútbol',
    description: 'Programa de iniciación al fútbol para niños. Desarrollo de habilidades básicas y trabajo en equipo.',
    schedule: 'Lunes, Miércoles y Viernes 4:00 PM - 5:30 PM',
    price_monthly: 180000,
    age_min: 6,
    age_max: 11,
    max_participants: 25,
    current_participants: 18,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400',
  },
  {
    id: 'prog-2',
    school_id: 'demo-school-1',
    name: 'Fútbol Juvenil (12-17 años)',
    sport: 'Fútbol',
    description: 'Formación avanzada para jóvenes talentos. Preparación física y técnica profesional.',
    schedule: 'Martes, Jueves y Sábado 3:00 PM - 5:00 PM',
    price_monthly: 220000,
    age_min: 12,
    age_max: 17,
    max_participants: 20,
    current_participants: 15,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400',
  },
  {
    id: 'prog-3',
    school_id: 'demo-school-1',
    name: 'Fútbol Adultos',
    sport: 'Fútbol',
    description: 'Liga recreativa para mayores de 18 años. Partidos semanales y torneos mensuales.',
    schedule: 'Sábados 8:00 AM - 10:00 AM',
    price_monthly: 150000,
    age_min: 18,
    age_max: null,
    max_participants: 30,
    current_participants: 22,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400',
  },
  // Natación Atanasio
  {
    id: 'prog-4',
    school_id: 'demo-school-2',
    name: 'Natación Bebés (6 meses - 3 años)',
    sport: 'Natación',
    description: 'Estimulación acuática temprana con acompañamiento de padres. Ambiente cálido y seguro.',
    schedule: 'Martes y Jueves 9:00 AM - 9:45 AM',
    price_monthly: 200000,
    age_min: 0,
    age_max: 3,
    max_participants: 12,
    current_participants: 10,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1560090995-01632a28895b?w=400',
  },
  {
    id: 'prog-5',
    school_id: 'demo-school-2',
    name: 'Natación Competitiva',
    sport: 'Natación',
    description: 'Programa de alto rendimiento. Participación en competencias regionales y nacionales.',
    schedule: 'Lunes a Viernes 5:00 AM - 7:00 AM',
    price_monthly: 350000,
    age_min: 10,
    age_max: 25,
    max_participants: 15,
    current_participants: 12,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400',
  },
  // Tenis Cali
  {
    id: 'prog-6',
    school_id: 'demo-school-3',
    name: 'Tenis Niños Iniciación',
    sport: 'Tenis',
    description: 'Primeros pasos en el tenis. Metodología Play+Stay para aprender jugando.',
    schedule: 'Sábados 9:00 AM - 10:30 AM',
    price_monthly: 160000,
    age_min: 5,
    age_max: 10,
    max_participants: 16,
    current_participants: 14,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1551773188-0801da12ddae?w=400',
  },
  {
    id: 'prog-7',
    school_id: 'demo-school-3',
    name: 'Tenis Adultos',
    sport: 'Tenis',
    description: 'Clases grupales e individuales para todos los niveles. Torneos internos mensuales.',
    schedule: 'Lunes, Miércoles y Viernes 7:00 PM - 8:30 PM',
    price_monthly: 250000,
    age_min: 18,
    age_max: null,
    max_participants: 12,
    current_participants: 8,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=400',
  },
  // Baloncesto Caribe
  {
    id: 'prog-8',
    school_id: 'demo-school-4',
    name: 'Mini Basket (5-8 años)',
    sport: 'Baloncesto',
    description: 'Introducción al baloncesto adaptado para los más pequeños con canastas y balones mini.',
    schedule: 'Sábados 10:00 AM - 11:30 AM',
    price_monthly: 140000,
    age_min: 5,
    age_max: 8,
    max_participants: 20,
    current_participants: 16,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=400',
  },
  // Artes Marciales
  {
    id: 'prog-9',
    school_id: 'demo-school-5',
    name: 'Karate Infantil',
    sport: 'Karate',
    description: 'Formación en karate tradicional. Desarrollo de disciplina, respeto y autoconfianza.',
    schedule: 'Martes y Jueves 5:00 PM - 6:30 PM',
    price_monthly: 170000,
    age_min: 6,
    age_max: 12,
    max_participants: 18,
    current_participants: 15,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400',
  },
];

// Demo products for the store
export const demoProducts = [
  {
    id: 'product-1',
    name: 'Balón de Fútbol Profesional Nike',
    description: 'Balón oficial de la Liga Colombiana. Tecnología Aerowsculpt para mayor precisión.',
    price: 189000,
    category: 'Fútbol',
    stock: 25,
    discount: 15,
    image_url: 'https://images.unsplash.com/photo-1614632537197-38a17061c2bd?w=400',
    rating: 4.8,
    reviews_count: 45,
  },
  {
    id: 'product-2',
    name: 'Gafas de Natación Speedo Vanquisher',
    description: 'Gafas de competición con protección UV y antivaho. Ajuste personalizable.',
    price: 85000,
    category: 'Natación',
    stock: 40,
    discount: 0,
    image_url: 'https://images.unsplash.com/photo-1622629797619-c100e3e67e2e?w=400',
    rating: 4.9,
    reviews_count: 78,
  },
  {
    id: 'product-3',
    name: 'Raqueta de Tenis Wilson Pro Staff',
    description: 'Raqueta de nivel avanzado utilizada por Roger Federer. Marco de grafito.',
    price: 850000,
    category: 'Tenis',
    stock: 8,
    discount: 10,
    image_url: 'https://images.unsplash.com/photo-1617083934555-ac7b4d0c8be7?w=400',
    rating: 4.7,
    reviews_count: 32,
  },
  {
    id: 'product-4',
    name: 'Uniforme de Karate Tokaido',
    description: 'Karategui de entrenamiento. Algodón 100% de alta calidad. Incluye cinturón blanco.',
    price: 220000,
    category: 'Artes Marciales',
    stock: 15,
    discount: 0,
    image_url: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400',
    rating: 4.6,
    reviews_count: 23,
  },
  {
    id: 'product-5',
    name: 'Balón de Baloncesto Spalding NBA',
    description: 'Balón oficial de la NBA. Cuero compuesto para interior y exterior.',
    price: 145000,
    category: 'Baloncesto',
    stock: 3,
    discount: 20,
    image_url: 'https://images.unsplash.com/photo-1494199505258-5f95387f933c?w=400',
    rating: 4.9,
    reviews_count: 89,
  },
  {
    id: 'product-6',
    name: 'Casco Ciclismo Specialized',
    description: 'Casco de alta protección con ventilación aerodinámica. Certificación CE.',
    price: 320000,
    category: 'Ciclismo',
    stock: 12,
    discount: 5,
    image_url: 'https://images.unsplash.com/photo-1557803175-2f8c4e19e95c?w=400',
    rating: 4.8,
    reviews_count: 56,
  },
];
